In [1]:
import numpy as np

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [72]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

In [75]:
a + b

array([[ 5, -3],
       [ 3,  5]])

In [73]:
np.dot(a, b)

array([[  4, -11],
       [ 12,  -3]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [80]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])

In [81]:
3*a-2*b+4*c

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [76]:
a = np.array([[4, 1], [5, -2], [2, 3]])
a

array([[ 4,  1],
       [ 5, -2],
       [ 2,  3]])

In [78]:
np.dot(a, a.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [79]:
np.dot(a.T, a)

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [66]:
a = np.random.randint(0, 20, (3, 6))
b = np.random.randint(0, 20, (6, 9))
print('Матрица а:\n', a)
print('Матрица b:\n', b)

Матрица а:
 [[ 3 15  2 18 19  9]
 [ 1 19  6 12  0 16]
 [ 9 13 11  5  9  7]]
Матрица b:
 [[ 0  2  1  0  0 18  1  0 13]
 [ 9 17  8  0 15 15 18  8  5]
 [ 6 17  8  9  6 15  7 14 15]
 [ 0 10  3  0  9  7 11  1 14]
 [11 10 17  8  9  7 10 18  2]
 [ 4  0  8 17  8  0 14 18 14]]


In [70]:
def matrix_dot(a, b):
    n = b.shape[0]
    if a.shape[1] == n:
        a_x_b = np.zeros((a.shape[0], b.shape[1]))
        for i in range(b.shape[1]):
            b_i = np.zeros((n, 1))
            for v in range(n):
                b_i[v] = b[v, i]
            for j in range(a.shape[0]):
                new_value = 0
                for k in range(a.shape[1]):
                    new_value += a[j][k]*b_i[k]
                a_x_b[j, i] = new_value
        return a_x_b
    else:
        return 'Матрицы не перемножаются'

In [71]:
print(matrix_dot(a, b))

[[392. 665. 588. 323. 642. 568. 801. 670. 560.]
 [271. 547. 365. 326. 557. 477. 741. 536. 590.]
 [310. 566. 425. 290. 443. 620. 563. 551. 533.]]


In [69]:
print(f'Проверяем:\n{np.dot(a, b)}')

Проверяем:
[[392 665 588 323 642 568 801 670 560]
 [271 547 365 326 557 477 741 536 590]
 [310 566 425 290 443 620 563 551 533]]


__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

#### п.а решил на листочке

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

In [82]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(a)

180.0

   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [92]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
round(np.linalg.det(a), -10)

-0.0

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [94]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
np.linalg.det(a)

0.0

#### Ответ: матрица вырожденная

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

In [95]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
np.linalg.matrix_rank(a)

2

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [96]:
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(a)

3